--------------------------------------------------------
--  Fichier créé - mercredi-décembre-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN_CLIENTS
--------------------------------------------------------

  CREATE TABLE "KARIM"."ADMIN_CLIENTS" 
   (	"LOGIN" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADMIN_COMMANDES
--------------------------------------------------------

  CREATE TABLE "KARIM"."ADMIN_COMMANDES" 
   (	"LOGIN" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADMIN_EMPLOYES
--------------------------------------------------------

  CREATE TABLE "KARIM"."ADMIN_EMPLOYES" 
   (	"LOGIN" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADMIN_FINANCES
--------------------------------------------------------

  CREATE TABLE "KARIM"."ADMIN_FINANCES" 
   (	"LOGIN" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADMIN_FOURNISSEURS
--------------------------------------------------------

  CREATE TABLE "KARIM"."ADMIN_FOURNISSEURS" 
   (	"LOGIN" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADMIN_GENERAL
--------------------------------------------------------

  CREATE TABLE "KARIM"."ADMIN_GENERAL" 
   (	"LOGIN" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADMIN_PRODUITS
--------------------------------------------------------

  CREATE TABLE "KARIM"."ADMIN_PRODUITS" 
   (	"LOGIN" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AJOUT_EMP_ADMIN
--------------------------------------------------------

  CREATE TABLE "KARIM"."AJOUT_EMP_ADMIN" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"LOGIN" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CAPITALE
--------------------------------------------------------

  CREATE TABLE "KARIM"."CAPITALE" 
   (	"BUDGET" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHILDEN
--------------------------------------------------------

  CREATE TABLE "KARIM"."CHILDEN" 
   (	"CHILD_ID" NUMBER, 
	"FIRSTNAME" VARCHAR2(50 BYTE), 
	"CHILD_LASTNAME" VARCHAR2(50 BYTE), 
	"BIRTH_DATE" DATE, 
	"EMPLOYEE_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "KARIM"."CLIENT" 
   (	"CIN" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"AGE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "KARIM"."CLIENTS" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"NBR_POINT" NUMBER, 
	"NUM_TELEPHONE" NUMBER, 
	"ID_COMMANDE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDES
--------------------------------------------------------

  CREATE TABLE "KARIM"."COMMANDES" 
   (	"ID_COMMANDE" NUMBER, 
	"QUANTITE" NUMBER, 
	"ENCAISSEMENT" VARCHAR2(225 BYTE), 
	"SERVICE" VARCHAR2(225 BYTE), 
	"RECLAMATION" VARCHAR2(225 BYTE), 
	"DATECOMMANDE" DATE, 
	"CIN_C" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPARTEMENTS
--------------------------------------------------------

  CREATE TABLE "KARIM"."DEPARTEMENTS" 
   (	"ID_DEPARTEMENT" NUMBER, 
	"NOM_DEPARTEMENT" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "KARIM"."EMPLOYES" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(256 BYTE), 
	"PRENOM" VARCHAR2(256 BYTE), 
	"EMAIL" VARCHAR2(256 BYTE), 
	"POSTE" VARCHAR2(256 BYTE), 
	"SALAIRE" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FINANCES
--------------------------------------------------------

  CREATE TABLE "KARIM"."FINANCES" 
   (	"ID_FACTURE" NUMBER, 
	"DATE_FACTURE" DATE, 
	"REFERENCE" VARCHAR2(20 BYTE), 
	"PRIX" FLOAT(126), 
	"STATISTIQUE" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEURS
--------------------------------------------------------

  CREATE TABLE "KARIM"."FOURNISSEURS" 
   (	"ID_FOURNISSEURS" NUMBER, 
	"NOM" VARCHAR2(50 BYTE), 
	"ADRESSE" VARCHAR2(200 BYTE), 
	"CATEGORIE" VARCHAR2(50 BYTE), 
	"LOGO" VARCHAR2(200 BYTE), 
	"NUM" LONG
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HISTORIQUES
--------------------------------------------------------

  CREATE TABLE "KARIM"."HISTORIQUES" 
   (	"HID" NUMBER, 
	"HDATE" DATE, 
	"HREF" VARCHAR2(20 BYTE), 
	"HPRIX" FLOAT(126), 
	"HSTAT" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIVRAISONS
--------------------------------------------------------

  CREATE TABLE "KARIM"."LIVRAISONS" 
   (	"ID_LIVRAISON" NUMBER, 
	"ADRESSE" VARCHAR2(255 BYTE), 
	"FACTURATION" VARCHAR2(255 BYTE), 
	"CIN_E" NUMBER, 
	"ID_COMMANDE" NUMBER, 
	"DATELIVRAISON" DATE, 
	"MAPS" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONNES
--------------------------------------------------------

  CREATE TABLE "KARIM"."PERSONNES" 
   (	"NOM" VARCHAR2(100 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"ADRESSE" VARCHAR2(50 BYTE) DEFAULT 'Tunis', 
	"DATENAISSANCE" DATE, 
	"ID_DEPART" NUMBER, 
	"TELEPHONE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUITS
--------------------------------------------------------

  CREATE TABLE "KARIM"."PRODUITS" 
   (	"TYPE" VARCHAR2(100 BYTE), 
	"PRIX" VARCHAR2(100 BYTE), 
	"QUANTITE" VARCHAR2(100 BYTE), 
	"ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "KARIM"."TEST" 
   (	"NOM" VARCHAR2(50 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"ID" NUMBER, 
	"NUM_TEL" NUMBER, 
	"SALARY" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into KARIM.ADMIN_CLIENTS
SET DEFINE OFF;
Insert into KARIM.ADMIN_CLIENTS (LOGIN,MDP) values ('nour','nour');
Insert into KARIM.ADMIN_CLIENTS (LOGIN,MDP) values ('sudo','sudo');
REM INSERTING into KARIM.ADMIN_COMMANDES
SET DEFINE OFF;
Insert into KARIM.ADMIN_COMMANDES (LOGIN,MDP) values ('slim','slim');
Insert into KARIM.ADMIN_COMMANDES (LOGIN,MDP) values ('sudo','sudo');
REM INSERTING into KARIM.ADMIN_EMPLOYES
SET DEFINE OFF;
Insert into KARIM.ADMIN_EMPLOYES (LOGIN,MDP) values ('oussama','oussama');
Insert into KARIM.ADMIN_EMPLOYES (LOGIN,MDP) values ('sudo','sudo');
REM INSERTING into KARIM.ADMIN_FINANCES
SET DEFINE OFF;
Insert into KARIM.ADMIN_FINANCES (LOGIN,MDP) values ('brahim','brahim');
Insert into KARIM.ADMIN_FINANCES (LOGIN,MDP) values ('sudo','sudo');
REM INSERTING into KARIM.ADMIN_FOURNISSEURS
SET DEFINE OFF;
Insert into KARIM.ADMIN_FOURNISSEURS (LOGIN,MDP) values ('karim','karim');
Insert into KARIM.ADMIN_FOURNISSEURS (LOGIN,MDP) values ('sudo','sudo');
REM INSERTING into KARIM.ADMIN_GENERAL
SET DEFINE OFF;
Insert into KARIM.ADMIN_GENERAL (LOGIN,MDP) values ('oussama','oussama');
Insert into KARIM.ADMIN_GENERAL (LOGIN,MDP) values ('nour','nour');
Insert into KARIM.ADMIN_GENERAL (LOGIN,MDP) values ('farah','farah');
Insert into KARIM.ADMIN_GENERAL (LOGIN,MDP) values ('sudo','sudo');
Insert into KARIM.ADMIN_GENERAL (LOGIN,MDP) values ('slim','slim');
Insert into KARIM.ADMIN_GENERAL (LOGIN,MDP) values ('brahim','brahim');
Insert into KARIM.ADMIN_GENERAL (LOGIN,MDP) values ('karim','karim');
REM INSERTING into KARIM.ADMIN_PRODUITS
SET DEFINE OFF;
Insert into KARIM.ADMIN_PRODUITS (LOGIN,MDP) values ('farah','farah');
Insert into KARIM.ADMIN_PRODUITS (LOGIN,MDP) values ('sudo','sudo');
REM INSERTING into KARIM.AJOUT_EMP_ADMIN
SET DEFINE OFF;
Insert into KARIM.AJOUT_EMP_ADMIN (NOM,MDP,PRENOM,LOGIN) values ('gammoudi','oussama','oussama','oussama');
Insert into KARIM.AJOUT_EMP_ADMIN (NOM,MDP,PRENOM,LOGIN) values ('sudo','sudo','sudo','sudo');
Insert into KARIM.AJOUT_EMP_ADMIN (NOM,MDP,PRENOM,LOGIN) values ('thraya','nour','nour','nour');
Insert into KARIM.AJOUT_EMP_ADMIN (NOM,MDP,PRENOM,LOGIN) values ('battikh','farah','farah','farah');
Insert into KARIM.AJOUT_EMP_ADMIN (NOM,MDP,PRENOM,LOGIN) values ('drira','slim','slim','slim');
Insert into KARIM.AJOUT_EMP_ADMIN (NOM,MDP,PRENOM,LOGIN) values ('akkari','karim','karim','karim');
Insert into KARIM.AJOUT_EMP_ADMIN (NOM,MDP,PRENOM,LOGIN) values ('abdelbeki','brahim','brahim','brahim');
REM INSERTING into KARIM.CAPITALE
SET DEFINE OFF;
Insert into KARIM.CAPITALE (BUDGET) values ('46000');
REM INSERTING into KARIM.CHILDEN
SET DEFINE OFF;
REM INSERTING into KARIM.CLIENT
SET DEFINE OFF;
REM INSERTING into KARIM.CLIENTS
SET DEFINE OFF;
Insert into KARIM.CLIENTS (CIN,NOM,PRENOM,ADRESSE,EMAIL,NBR_POINT,NUM_TELEPHONE,ID_COMMANDE) values ('55','nnn','hhh','hhh','hhh','0','555','0');
REM INSERTING into KARIM.COMMANDES
SET DEFINE OFF;
REM INSERTING into KARIM.DEPARTEMENTS
SET DEFINE OFF;
Insert into KARIM.DEPARTEMENTS (ID_DEPARTEMENT,NOM_DEPARTEMENT) values ('10','Dept10');
Insert into KARIM.DEPARTEMENTS (ID_DEPARTEMENT,NOM_DEPARTEMENT) values ('20','Dept20');
Insert into KARIM.DEPARTEMENTS (ID_DEPARTEMENT,NOM_DEPARTEMENT) values ('30','Dept30');
REM INSERTING into KARIM.EMPLOYES
SET DEFINE OFF;
Insert into KARIM.EMPLOYES (CIN,NOM,PRENOM,EMAIL,POSTE,SALAIRE) values ('123','Gammoudi','Oussama','oussama.gammoudi@esprit.tn','RH','5000');
Insert into KARIM.EMPLOYES (CIN,NOM,PRENOM,EMAIL,POSTE,SALAIRE) values ('1234','Akkari','Karim','Karim.akkari@esprit.tn','Dev','3000');
REM INSERTING into KARIM.FINANCES
SET DEFINE OFF;
Insert into KARIM.FINANCES (ID_FACTURE,DATE_FACTURE,REFERENCE,PRIX,STATISTIQUE) values ('1',to_date('25/04/22','DD/MM/RR'),'Abhq454','2000','4');
REM INSERTING into KARIM.FOURNISSEURS
SET DEFINE OFF;
Insert into KARIM.FOURNISSEURS (ID_FOURNISSEURS,NOM,ADRESSE,CATEGORIE,LOGO,NUM) values ('1','tunisianet','alain savari','Materiel Bureautique','alain savari','71658230');
Insert into KARIM.FOURNISSEURS (ID_FOURNISSEURS,NOM,ADRESSE,CATEGORIE,LOGO,NUM) values ('2','mytek','charguia','Materiel Bureautique','charguia','70526321');
Insert into KARIM.FOURNISSEURS (ID_FOURNISSEURS,NOM,ADRESSE,CATEGORIE,LOGO,NUM) values ('3','bestphone','ennasr 1','Materiel Portable','ennasr 1','21523654');
Insert into KARIM.FOURNISSEURS (ID_FOURNISSEURS,NOM,ADRESSE,CATEGORIE,LOGO,NUM) values ('4','paperyo','kram','Materiel pour imprimantes ','kram','75362541');
REM INSERTING into KARIM.HISTORIQUES
SET DEFINE OFF;
Insert into KARIM.HISTORIQUES (HID,HDATE,HREF,HPRIX,HSTAT) values ('1',to_date('25/04/22','DD/MM/RR'),'Abhq454','2000','4');
Insert into KARIM.HISTORIQUES (HID,HDATE,HREF,HPRIX,HSTAT) values ('1',to_date('25/04/22','DD/MM/RR'),'Abhq454','2000','4,16667');
REM INSERTING into KARIM.LIVRAISONS
SET DEFINE OFF;
REM INSERTING into KARIM.PERSONNES
SET DEFINE OFF;
Insert into KARIM.PERSONNES (NOM,PRENOM,ADRESSE,DATENAISSANCE,ID_DEPART,TELEPHONE) values ('Bensalah','Ahmed','12 rue elbhira 2080 Tunis',to_date('09/11/84','DD/MM/RR'),'10','22314589');
Insert into KARIM.PERSONNES (NOM,PRENOM,ADRESSE,DATENAISSANCE,ID_DEPART,TELEPHONE) values ('Aidli','Salma','18 rue elbasra 2082 Tunis',to_date('19/01/82','DD/MM/RR'),'10','98001203');
Insert into KARIM.PERSONNES (NOM,PRENOM,ADRESSE,DATENAISSANCE,ID_DEPART,TELEPHONE) values ('Ferchichi','Adel','21 rue municipalite 2082 Tunis',to_date('21/01/80','DD/MM/RR'),'20','94657123');
Insert into KARIM.PERSONNES (NOM,PRENOM,ADRESSE,DATENAISSANCE,ID_DEPART,TELEPHONE) values ('Berhouma','Samia','17 rue habit 2082 Tunis ',to_date('18/08/80','DD/MM/RR'),'30','94657123');
REM INSERTING into KARIM.PRODUITS
SET DEFINE OFF;
Insert into KARIM.PRODUITS (TYPE,PRIX,QUANTITE,ID) values ('14','12000','550000','12');
Insert into KARIM.PRODUITS (TYPE,PRIX,QUANTITE,ID) values ('14','550000','12000','122222');
REM INSERTING into KARIM.TEST
SET DEFINE OFF;
Insert into KARIM.TEST (NOM,PRENOM,ID,NUM_TEL,SALARY) values ('karim','akkari','1','28446211',null);
Insert into KARIM.TEST (NOM,PRENOM,ID,NUM_TEL,SALARY) values ('aziz','akkari','2','24910501',null);
--------------------------------------------------------
--  DDL for Index ADMIN_PRODUITS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."ADMIN_PRODUITS_PK" ON "KARIM"."ADMIN_PRODUITS" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADMIN_CLIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."ADMIN_CLIENTS_PK" ON "KARIM"."ADMIN_CLIENTS" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_NUMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."PK_NUMBER" ON "KARIM"."TEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADMIN_COMMANDES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."ADMIN_COMMANDES_PK" ON "KARIM"."ADMIN_COMMANDES" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."TABLE1_PK" ON "KARIM"."EMPLOYES" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FINANCES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."FINANCES_PK" ON "KARIM"."FINANCES" ("ID_FACTURE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."CLIENTS_PK" ON "KARIM"."CLIENTS" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_DEPARTEMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."PK_DEPARTEMENT" ON "KARIM"."DEPARTEMENTS" ("ID_DEPARTEMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADMIN_FOURNISSEURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."ADMIN_FOURNISSEURS_PK" ON "KARIM"."ADMIN_FOURNISSEURS" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMANDES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."COMMANDES_PK" ON "KARIM"."COMMANDES" ("ID_COMMANDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADMIN_EMPLOYES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."ADMIN_EMPLOYES_PK" ON "KARIM"."ADMIN_EMPLOYES" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AJOUT_EMP_ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."AJOUT_EMP_ADMIN_PK" ON "KARIM"."AJOUT_EMP_ADMIN" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."CLIENT_PK" ON "KARIM"."CLIENT" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LIVRAISONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."LIVRAISONS_PK" ON "KARIM"."LIVRAISONS" ("ID_LIVRAISON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."ADMIN_PK" ON "KARIM"."ADMIN_GENERAL" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADMIN_FINANCES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."ADMIN_FINANCES_PK" ON "KARIM"."ADMIN_FINANCES" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PERSONNE
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."PK_PERSONNE" ON "KARIM"."PERSONNES" ("NOM", "PRENOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNISSEURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."FOURNISSEURS_PK" ON "KARIM"."FOURNISSEURS" ("ID_FOURNISSEURS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CHILDEN
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARIM"."PK_CHILDEN" ON "KARIM"."CHILDEN" ("CHILD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COMMANDES
--------------------------------------------------------

  ALTER TABLE "KARIM"."COMMANDES" ADD CONSTRAINT "COMMANDES_PK" PRIMARY KEY ("ID_COMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KARIM"."COMMANDES" MODIFY ("ID_COMMANDE" NOT NULL ENABLE);
 
  ALTER TABLE "KARIM"."COMMANDES" MODIFY ("CIN_C" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HISTORIQUES
--------------------------------------------------------

  ALTER TABLE "KARIM"."HISTORIQUES" MODIFY ("HID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FINANCES
--------------------------------------------------------

  ALTER TABLE "KARIM"."FINANCES" ADD CONSTRAINT "FINANCES_PK" PRIMARY KEY ("ID_FACTURE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KARIM"."FINANCES" MODIFY ("ID_FACTURE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNISSEURS
--------------------------------------------------------

  ALTER TABLE "KARIM"."FOURNISSEURS" ADD CONSTRAINT "FOURNISSEURS_PK" PRIMARY KEY ("ID_FOURNISSEURS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KARIM"."FOURNISSEURS" MODIFY ("ID_FOURNISSEURS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "KARIM"."EMPLOYES" MODIFY ("CIN" NOT NULL ENABLE);
 
  ALTER TABLE "KARIM"."EMPLOYES" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIVRAISONS
--------------------------------------------------------

  ALTER TABLE "KARIM"."LIVRAISONS" ADD CONSTRAINT "LIVRAISONS_PK" PRIMARY KEY ("ID_LIVRAISON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KARIM"."LIVRAISONS" MODIFY ("ID_LIVRAISON" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMIN_FINANCES
--------------------------------------------------------

  ALTER TABLE "KARIM"."ADMIN_FINANCES" ADD CONSTRAINT "ADMIN_FINANCES_PK" PRIMARY KEY ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KARIM"."ADMIN_FINANCES" MODIFY ("LOGIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AJOUT_EMP_ADMIN
--------------------------------------------------------

  ALTER TABLE "KARIM"."AJOUT_EMP_ADMIN" ADD CONSTRAINT "AJOUT_EMP_ADMIN_PK" PRIMARY KEY ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KARIM"."AJOUT_EMP_ADMIN" MODIFY ("LOGIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAPITALE
--------------------------------------------------------

  ALTER TABLE "KARIM"."CAPITALE" MODIFY ("BUDGET" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "KARIM"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KARIM"."CLIENT" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMIN_PRODUITS
--------------------------------------------------------

  ALTER TABLE "KARIM"."ADMIN_PRODUITS" ADD CONSTRAINT "ADMIN_PRODUITS_PK" PRIMARY KEY ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KARIM"."ADMIN_PRODUITS" MODIFY ("LOGIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMIN_FOURNISSEURS
--------------------------------------------------------

  ALTER TABLE "KARIM"."ADMIN_FOURNISSEURS" ADD CONSTRAINT "ADMIN_FOURNISSEURS_PK" PRIMARY KEY ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KARIM"."ADMIN_FOURNISSEURS" MODIFY ("LOGIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTEMENTS
--------------------------------------------------------

  ALTER TABLE "KARIM"."DEPARTEMENTS" ADD CONSTRAINT "CHECK_NOM_DEPARTEMENT" CHECK ( Nom_Departement like 'Dept%') ENABLE;
 
  ALTER TABLE "KARIM"."DEPARTEMENTS" ADD CONSTRAINT "PK_DEPARTEMENT" PRIMARY KEY ("ID_DEPARTEMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KARIM"."DEPARTEMENTS" MODIFY ("ID_DEPARTEMENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMIN_CLIENTS
--------------------------------------------------------

  ALTER TABLE "KARIM"."ADMIN_CLIENTS" ADD CONSTRAINT "ADMIN_CLIENTS_PK" PRIMARY KEY ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KARIM"."ADMIN_CLIENTS" MODIFY ("LOGIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMIN_EMPLOYES
--------------------------------------------------------

  ALTER TABLE "KARIM"."ADMIN_EMPLOYES" ADD CONSTRAINT "ADMIN_EMPLOYES_PK" PRIMARY KEY ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KARIM"."ADMIN_EMPLOYES" MODIFY ("LOGIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONNES
--------------------------------------------------------

  ALTER TABLE "KARIM"."PERSONNES" ADD CONSTRAINT "PK_PERSONNE" PRIMARY KEY ("NOM", "PRENOM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KARIM"."PERSONNES" MODIFY ("NOM" NOT NULL ENABLE);
 
  ALTER TABLE "KARIM"."PERSONNES" MODIFY ("PRENOM" NOT NULL ENABLE);
 
  ALTER TABLE "KARIM"."PERSONNES" MODIFY ("ADRESSE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHILDEN
--------------------------------------------------------

  ALTER TABLE "KARIM"."CHILDEN" ADD CONSTRAINT "PK_CHILDEN" PRIMARY KEY ("CHILD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KARIM"."CHILDEN" MODIFY ("CHILD_LASTNAME" NOT NULL ENABLE);
 
  ALTER TABLE "KARIM"."CHILDEN" ADD UNIQUE ("FIRSTNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMIN_COMMANDES
--------------------------------------------------------

  ALTER TABLE "KARIM"."ADMIN_COMMANDES" ADD CONSTRAINT "ADMIN_COMMANDES_PK" PRIMARY KEY ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KARIM"."ADMIN_COMMANDES" MODIFY ("LOGIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "KARIM"."TEST" ADD CONSTRAINT "PK_NUMBER" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KARIM"."TEST" MODIFY ("NOM" NOT NULL ENABLE);
 
  ALTER TABLE "KARIM"."TEST" MODIFY ("PRENOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMIN_GENERAL
--------------------------------------------------------

  ALTER TABLE "KARIM"."ADMIN_GENERAL" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KARIM"."ADMIN_GENERAL" MODIFY ("LOGIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "KARIM"."CLIENTS" ADD CONSTRAINT "CLIENTS_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "KARIM"."CLIENTS" MODIFY ("CIN" NOT NULL ENABLE);
 
  ALTER TABLE "KARIM"."CLIENTS" MODIFY ("ID_COMMANDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COMMANDES
--------------------------------------------------------

  ALTER TABLE "KARIM"."COMMANDES" ADD CONSTRAINT "COMMANDES_FK1" FOREIGN KEY ("CIN_C")
	  REFERENCES "KARIM"."CLIENTS" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIVRAISONS
--------------------------------------------------------

  ALTER TABLE "KARIM"."LIVRAISONS" ADD CONSTRAINT "LIVRAISONS_FK1" FOREIGN KEY ("ID_COMMANDE")
	  REFERENCES "KARIM"."COMMANDES" ("ID_COMMANDE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONNES
--------------------------------------------------------

  ALTER TABLE "KARIM"."PERSONNES" ADD CONSTRAINT "FK_PERSONNE_ID_DEPART" FOREIGN KEY ("ID_DEPART")
	  REFERENCES "KARIM"."DEPARTEMENTS" ("ID_DEPARTEMENT") ENABLE;
